### ISSUE TITLE
[Question] Provided pre-built binaries releases

### ISSUE THREAD

**Issue by pramodk** [spatial-model-editor/sme_deps_llvm#1]
Hello @lkeegan,

I see that the releases provided on [README](https://github.com/lkeegan/llvm-static#llvm-static--) contain only libraries and not binaries.

Just curious why binaries are not packaged. Have you seen any issue?

In one of our package (NEURON/CoreNEURON/NMODL - which you know!), we need to ship full compiling environment (for NMODL) and hence was wondering about shipping pre-built LLVM binaries (with binary installers or even for python wheels).

cc: @ferdonline @iomaganaris

**Comment by lkeegan** [comment]
Hi @pramodk!

The only reason the binaries are not packaged is that for <https://github.com/lkeegan/spatial-model-editor/> all we need are the libraries, and the binaries are quite big.

I haven't seen any issues with the binaries (but also haven't tried shipping them).

**Comment by pramodk** [comment]
Thanks Liam for clarification!  I will fork this and will try enabling binaries. Will see how it goes!
